In [404]:
import pandas as pd

df = pd.read_csv('divorce-csv.csv')
df

,Atr1,Atr2,Atr3,Atr4,Atr5,Atr6,Atr7,Atr8,Atr9,Atr10,...,Atr46,Atr47,Atr48,Atr49,Atr50,Atr51,Atr52,Atr53,Atr54,Class
0,2,2,4,1,0,0,0,0,0,0,...,2,1,3,3,3,2,3,2,1,1
1,4,4,4,4,4,0,0,4,4,4,...,2,2,3,4,4,4,4,2,2,1
2,2,2,2,2,1,3,2,1,1,2,...,3,2,3,1,1,1,2,2,2,1
3,3,2,3,2,3,3,3,3,3,3,...,2,2,3,3,3,3,2,2,2,1
4,2,2,1,1,1,1,0,0,0,0,...,2,1,2,3,2,2,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,0,0,0,0,0,0,0,0,0,0,...,1,0,4,1,1,4,2,2,2,0
166,0,0,0,0,0,0,0,0,0,0,...,4,1,2,2,2,2,3,2,2,0
167,1,1,0,0,0,0,0,0,0,1,...,3,0,2,0,1,1,3,0,0,0
168,0,0,0,0,0,0,0,0,0,0,...,3,3,2,2,3,2,4,3,1,0
169,0,0,0,0,0,0,0,1,0,0,...,3,4,4,0,1,3,3,3,1,0

<font face = 'Verdana'>  Attribute Information:
1. If one of us apologizes when our discussion deteriorates, the discussion ends.
2. I know we can ignore our differences, even if things get hard sometimes.
3. When we need it, we can take our discussions with my spouse from the beginning and correct it.
4. When I discuss with my spouse, to contact him will eventually work.
5. The time I spent with my wife is special for us.
6. We don't have time at home as partners.
7. We are like two strangers who share the same environment at home rather than family.
8. I enjoy our holidays with my wife.
9. I enjoy traveling with my wife.
10. Most of our goals are common to my spouse.
11. I think that one day in the future, when I look back, I see that my spouse and I have been in harmony with each other.
12. My spouse and I have similar values in terms of personal freedom.
13. My spouse and I have similar sense of entertainment.
14. Most of our goals for people (children, friends, etc.) are the same.
15. Our dreams with my spouse are similar and harmonious.
16. We're compatible with my spouse about what love should be.
17. We share the same views about being happy in our life with my spouse
18. My spouse and I have similar ideas about how marriage should be
19. My spouse and I have similar ideas about how roles should be in marriage
20. My spouse and I have similar values in trust.
21. I know exactly what my wife likes.
22. I know how my spouse wants to be taken care of when she/he sick.
23. I know my spouse's favorite food.
24. I can tell you what kind of stress my spouse is facing in her/his life.
25. I have knowledge of my spouse's inner world.
26. I know my spouse's basic anxieties.
27. I know what my spouse's current sources of stress are.
28. I know my spouse's hopes and wishes.
29. I know my spouse very well.
30. I know my spouse's friends and their social relationships.
31. I feel aggressive when I argue with my spouse.
32. When discussing with my spouse, I usually use expressions such as â€˜you alwaysâ€™ or â€˜you neverâ€™ .
33. I can use negative statements about my spouse's personality during our discussions.
34. I can use offensive expressions during our discussions.
35. I can insult my spouse during our discussions.
36. I can be humiliating when we discussions.
37. My discussion with my spouse is not calm.
38. I hate my spouse's way of open a subject.
39. Our discussions often occur suddenly.
40. We're just starting a discussion before I know what's going on.
41. When I talk to my spouse about something, my calm suddenly breaks.
42. When I argue with my spouse, Ä± only go out and I don't say a word.
43. I mostly stay silent to calm the environment a little bit.
44. Sometimes I think it's good for me to leave home for a while.
45. I'd rather stay silent than discuss with my spouse.
46. Even if I'm right in the discussion, I stay silent to hurt my spouse.
47. When I discuss with my spouse, I stay silent because I am afraid of not being able to control my anger.
48. I feel right in our discussions.
49. I have nothing to do with what I've been accused of.
50. I'm not actually the one who's guilty about what I'm accused of.
51. I'm not the one who's wrong about problems at home.
52. I wouldn't hesitate to tell my spouse about her/his inadequacy.
53. When I discuss, I remind my spouse of her/his inadequacy.
54. I'm not afraid to tell my spouse about her/his incompetence.

In [405]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 55 columns):
Atr1     170 non-null int64
Atr2     170 non-null int64
Atr3     170 non-null int64
Atr4     170 non-null int64
Atr5     170 non-null int64
Atr6     170 non-null int64
Atr7     170 non-null int64
Atr8     170 non-null int64
Atr9     170 non-null int64
Atr10    170 non-null int64
Atr11    170 non-null int64
Atr12    170 non-null int64
Atr13    170 non-null int64
Atr14    170 non-null int64
Atr15    170 non-null int64
Atr16    170 non-null int64
Atr17    170 non-null int64
Atr18    170 non-null int64
Atr19    170 non-null int64
Atr20    170 non-null int64
Atr21    170 non-null int64
Atr22    170 non-null int64
Atr23    170 non-null int64
Atr24    170 non-null int64
Atr25    170 non-null int64
Atr26    170 non-null int64
Atr27    170 non-null int64
Atr28    170 non-null int64
Atr29    170 non-null int64
Atr30    170 non-null int64
Atr31    170 non-null int64
Atr32    170 non-null int64
Atr33    170 non-null int64
Atr34    170 non-null int64
Atr35    170 non-null int64
Atr36    170 non-null int64
Atr37    170 non-null int64
Atr38    170 non-null int64
Atr39    170 non-null int64
Atr40    170 non-null int64
Atr41    170 non-null int64
Atr42    170 non-null int64
Atr43    170 non-null int64
Atr44    170 non-null int64
Atr45    170 non-null int64
Atr46    170 non-null int64
Atr47    170 non-null int64
Atr48    170 non-null int64
Atr49    170 non-null int64
Atr50    170 non-null int64
Atr51    170 non-null int64
Atr52    170 non-null int64
Atr53    170 non-null int64
Atr54    170 non-null int64
Class    170 non-null int64
dtypes: int64(55)
memory usage: 73.2 KB

In [406]:
X = df.iloc[:,:-1] # Columns from Art1 to Atr54
y = df.iloc[:,54] # Columns no 54 .i.e only

In [407]:
y

0      1
1      1
2      1
3      1
4      1
      ..
165    0
166    0
167    0
168    0
169    0
Name: Class, Length: 170, dtype: int64

In [408]:
from sklearn import linear_model

In [409]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.20, random_state =0)

In [410]:
#Using Regresstion Forest Algorithm , we are going to calculate the importance of all the columns.
from sklearn.ensemble import RandomForestRegressor
r_forest = RandomForestRegressor(n_estimators = 1000,random_state = 50)
r_forest.fit(X_train,y_train.values.ravel())

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1000,
                      n_jobs=None, oob_score=False, random_state=50, verbose=0,
                      warm_start=False)

In [411]:
col_names = X_train.columns.tolist()
print(col_names)
features_imp =pd.Series(r_forest.feature_importances_,index = col_names).sort_values(ascending = False)
#features_imp =pd.Series(r_forest.feature_importances_,index = col_names)
features_imp

['Atr1', 'Atr2', 'Atr3', 'Atr4', 'Atr5', 'Atr6', 'Atr7', 'Atr8', 'Atr9', 'Atr10', 'Atr11', 'Atr12', 'Atr13', 'Atr14', 'Atr15', 'Atr16', 'Atr17', 'Atr18', 'Atr19', 'Atr20', 'Atr21', 'Atr22', 'Atr23', 'Atr24', 'Atr25', 'Atr26', 'Atr27', 'Atr28', 'Atr29', 'Atr30', 'Atr31', 'Atr32', 'Atr33', 'Atr34', 'Atr35', 'Atr36', 'Atr37', 'Atr38', 'Atr39', 'Atr40', 'Atr41', 'Atr42', 'Atr43', 'Atr44', 'Atr45', 'Atr46', 'Atr47', 'Atr48', 'Atr49', 'Atr50', 'Atr51', 'Atr52', 'Atr53', 'Atr54']

Atr18    0.412707
Atr40    0.224100
Atr11    0.113181
Atr20    0.052243
Atr9     0.045002
Atr17    0.034678
Atr19    0.031535
Atr39    0.031004
Atr16    0.014000
Atr41    0.010885
Atr14    0.008117
Atr8     0.004972
Atr2     0.004028
Atr29    0.003000
Atr36    0.002115
Atr3     0.001601
Atr21    0.001086
Atr10    0.001060
Atr12    0.001057
Atr25    0.001000
Atr5     0.001000
Atr1     0.000203
Atr30    0.000175
Atr53    0.000145
Atr7     0.000117
Atr52    0.000116
Atr4     0.000116
Atr22    0.000116
Atr54    0.000115
Atr15    0.000091
Atr44    0.000086
Atr26    0.000058
Atr32    0.000058
Atr49    0.000058
Atr37    0.000058
Atr27    0.000029
Atr24    0.000029
Atr33    0.000029
Atr13    0.000029
Atr46    0.000000
Atr51    0.000000
Atr50    0.000000
Atr23    0.000000
Atr48    0.000000
Atr6     0.000000
Atr47    0.000000
Atr34    0.000000
Atr35    0.000000
Atr28    0.000000
Atr43    0.000000
Atr42    0.000000
Atr38    0.000000
Atr31    0.000000
Atr45    0.000000
dtype: float64

<font face="verdana">From above feature importance table , we can are using only top 8 columns and drop rest of the tables....
    i.e 
1. Atr9 
2. Atr8 
3. Atr18 
4. Atr17 
5. Atr15
6. Atr5
7. Atr11
8. Atr36

<font face="verdana"> <center><h2><font color = 'Red'> LINEAR REGRESSION</font></h2> </center>

<font face = 'Verdana'> <font color = "blue" >.....Since the Output variable is catagorical [1,0], hence Linear Regression is not to be applied..

In [412]:
from sklearn import linear_model
X = df[['Atr9','Atr8','Atr18','Atr17','Atr15','Atr5','Atr11','Atr36']]
y =  df['Class']

In [413]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.20, random_state = 100)

In [414]:
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)
print('coeficent',lm.coef_)
print('Intercept',lm.intercept_)
print('R square',lm.score(X_train,y_train))

coeficent [ 0.02169716 -0.08140219  0.15106003  0.09613138  0.02076688 -0.08166657
  0.08581203  0.08794332]
Intercept 0.009538986209252753
R square 0.9154215555248858

In [415]:
y_pred = lm.predict(X_test)
y_pred

array([ 0.85913384,  0.983412  ,  0.00953899,  0.00953899,  0.99850841,
        0.28164273,  0.82679254,  1.04097245,  0.00953899,  1.21090713,
        0.10567037,  1.03502049,  0.3633093 ,  0.10567037,  1.16844309,
        0.23301615,  0.00953899,  0.00953899,  1.22318023,  1.02912742,
        0.00953899,  0.00953899,  0.11611789, -0.04602059,  1.11477575,
        1.09878525, -0.05016605,  0.00953899,  0.92885058,  0.92885058,
        1.01084193,  0.99850841, -0.07186321,  0.09748231])

In [416]:
lin_reg_pred = y_pred

<font face="verdana"> <center><h2><font color = 'Red'> LOGISTIC REGRESSION</font></h2> </center>

In [417]:
#Now using logistic regression on training data
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

cla_log = LogisticRegression()
cla_log.fit(X_train,y_train)

C:\Users\Asus 1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [418]:
y_pred = cla_log.predict(X_test)
print('y_pred : ',y_pred)

y_pred :  [1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]

In [419]:
log_reg_pred = y_pred

In [420]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[18  0]
 [ 0 16]]

In [421]:
#accuracy
metrics.accuracy_score(y_test,y_pred)

1.0

<font face="verdana"> <center><h2><font color = 'Red'> K - Nearest Neighbour</font></h2> </center>

In [422]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [423]:
#make prediction for test data
y_pred = classifier.predict(X_test)
print(y_pred)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]

In [424]:
knn_pred = y_pred

In [425]:
#Evaluation

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy_score
accur = accuracy_score(y_test, y_pred)
print('Test Accuracy :{:.6f}'.format(accur))

[[18  0]
 [ 0 16]]
Test Accuracy :1.000000

<font face="verdana"> <center><h2><font color = 'Red'> Naive Baise</font></h2> </center>

In [426]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [427]:
#Creating our Naive Bayes Model using Sklearn
from sklearn.metrics import classification_report,confusion_matrix
model = GaussianNB()
model.fit(X_train,y_train)
#making prediction 
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

naive_pred = predicted

print(metrics.classification_report(expected,predicted))
#print(metrics.confusion_matrix((expected,predicted)))

from sklearn.metrics import accuracy_score
accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

<font face="verdana"> <center><h2><font color = 'Red'> SVM</font></h2> </center>

In [428]:
from sklearn.metrics import accuracy_score

print("model = svm.SVC(kernel = 'rbf', gamma = 'auto', degree = 4)\n")
model = svm.SVC(kernel = 'rbf', gamma = 'auto', degree = 4)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_rbf_auto_4pred = predicted
print(metrics.classification_report(expected,predicted))


accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'rbf', gamma = 'auto', degree = 4)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

In [429]:
print("model = svm.SVC(kernel = 'rbf', gamma = 'scale', degree = 4)\n")
model = svm.SVC(kernel = 'rbf', gamma = 'scale', degree = 4)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_rbf_scale_4pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'rbf', gamma = 'scale', degree = 4)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

In [430]:
print("model = svm.SVC(kernel = 'rbf', gamma = 'auto', degree = 3)\n")
model = svm.SVC(kernel = 'rbf', gamma = 'auto', degree =3)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_rbf_auto_3pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'rbf', gamma = 'auto', degree = 3)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

In [431]:
print("model = svm.SVC(kernel = 'rbf', gamma = 'scale', degree =3)\n")
model = svm.SVC(kernel = 'rbf', gamma = 'scale', degree =3)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_rbf_scale_3pred = predicted
print(metrics.classification_report(expected,predicted))

from sklearn.metrics import accuracy_score
accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'rbf', gamma = 'scale', degree =3)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

In [432]:
print("model = svm.SVC(kernel = 'linear', gamma = 'auto', degree =3)\n")
model = svm.SVC(kernel = 'linear', gamma = 'auto', degree =3)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_linear_auto_3pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'linear', gamma = 'auto', degree =3)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

In [433]:
print("model = svm.SVC(kernel = 'linear', gamma = 'scale', degree =3)\n")
model = svm.SVC(kernel = 'linear', gamma = 'scale', degree =3)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_linear_scale_3pred = predicted

print(metrics.classification_report(expected,predicted))
accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'linear', gamma = 'scale', degree =3)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        16

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Test Accuracy :1.000000

In [434]:
print("model = svm.SVC(kernel = 'sigmoid', gamma = 'auto', degree =3)\n")
model = svm.SVC(kernel = 'sigmoid', gamma = 'auto', degree =3)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_sigmoid_auto_3pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'sigmoid', gamma = 'auto', degree =3)

[0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 1 0 1]
              precision    recall  f1-score   support

           0       0.58      0.61      0.59        18
           1       0.53      0.50      0.52        16

    accuracy                           0.56        34
   macro avg       0.56      0.56      0.56        34
weighted avg       0.56      0.56      0.56        34

Test Accuracy :0.558824

In [435]:
print("model = svm.SVC(kernel = 'sigmoid', gamma = 'scale', degree =3)\n")
model = svm.SVC(kernel = 'sigmoid', gamma = 'scale', degree =3)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_sigmoid_scale_3pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'sigmoid', gamma = 'scale', degree =3)

[1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      0.78      0.88        18
           1       0.80      1.00      0.89        16

    accuracy                           0.88        34
   macro avg       0.90      0.89      0.88        34
weighted avg       0.91      0.88      0.88        34

Test Accuracy :0.882353

In [436]:
print("model = svm.SVC(kernel = 'sigmoid', gamma = 'auto', degree =4)\n")
model = svm.SVC(kernel = 'sigmoid', gamma = 'auto', degree =4)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_sigmoid_auto_4pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'sigmoid', gamma = 'auto', degree =4)

[0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 1 0 1]
              precision    recall  f1-score   support

           0       0.58      0.61      0.59        18
           1       0.53      0.50      0.52        16

    accuracy                           0.56        34
   macro avg       0.56      0.56      0.56        34
weighted avg       0.56      0.56      0.56        34

Test Accuracy :0.558824

In [437]:
print("model = svm.SVC(kernel = 'sigmoid', gamma = 'scale', degree =4)\n")
model = svm.SVC(kernel = 'sigmoid', gamma = 'scale', degree =4)
model.fit(X_train, y_train.values.ravel())
expected = y_test
predicted  = model.predict(X_test)
print(predicted)

SVM_sigmoid_scale_4pred = predicted
print(metrics.classification_report(expected,predicted))

accur = accuracy_score(expected,predicted)
print('Test Accuracy :{:.6f}'.format(accur))

model = svm.SVC(kernel = 'sigmoid', gamma = 'scale', degree =4)

[1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       1.00      0.78      0.88        18
           1       0.80      1.00      0.89        16

    accuracy                           0.88        34
   macro avg       0.90      0.89      0.88        34
weighted avg       0.91      0.88      0.88        34

Test Accuracy :0.882353

<font face="verdana"> <center><h2><font color = '#82E0AA'> Decision Tree Classifier</font></h2> </center>

In [438]:
from sklearn.tree import DecisionTreeClassifier
cla_dt=DecisionTreeClassifier()
cla_dt.fit(X_train,y_train)
print(cla_dt.score)

<bound method ClassifierMixin.score of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')>

In [439]:
y_pred=cla_dt.predict(X_test)
y_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [440]:
dt_pred = y_pred

In [441]:
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

Test Accuracy:0.970588

In [442]:
from sklearn.tree import DecisionTreeClassifier
cla_dt=DecisionTreeClassifier(criterion='entropy',max_depth =3,splitter ='random' )
cla_dt.fit(X_train,y_train)
print(cla_dt.score)
y_pred=cla_dt.predict(X_test)

<bound method ClassifierMixin.score of DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='random')>

In [443]:
y_pred=cla_dt.predict(X_test)
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [444]:
dt_entropy_3_random_pred = y_pred

In [445]:
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

Test Accuracy:1.000000

In [446]:
from sklearn.tree import DecisionTreeClassifier
cla_dt=DecisionTreeClassifier(criterion='entropy')
cla_dt.fit(X_train,y_train)
print(cla_dt.score)

<bound method ClassifierMixin.score of DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')>

In [447]:
y_pred=cla_dt.predict(X_test)
y_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [448]:
dt_entropy_pred = y_pred

In [449]:
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

Test Accuracy:0.970588

In [450]:
from sklearn.tree import DecisionTreeClassifier
cla_dt=DecisionTreeClassifier(criterion='entropy',max_depth =4,splitter ='random' )
cla_dt.fit(X_train,y_train)
print(cla_dt.score)

<bound method ClassifierMixin.score of DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='random')>

In [451]:
y_pred=cla_dt.predict(X_test)
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [452]:
dt_entropy_4_random_pred = y_pred

In [453]:
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

Test Accuracy:1.000000

<font face="verdana"> <center><h2><font color = '#82E0AA'> Random Forest Classifier</font></h2> </center>

In [454]:
#Now using  Random forests on  complete traning data
from sklearn.ensemble import RandomForestClassifier
cla_forest = RandomForestClassifier(n_estimators = 100)
cla_forest.fit(X_train,y_train)
#Predict 
y_pred = cla_forest.predict(X_test)
print(y_pred)
rt_100_pred = y_pred

from sklearn.metrics import accuracy_score
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
Test Accuracy:1.000000

In [455]:
cla_forest = RandomForestClassifier(n_estimators = 100,criterion ='entropy',max_depth = 4)
cla_forest.fit(X_train,y_train)
#Predict 
y_pred = cla_forest.predict(X_test)
print(y_pred)
rt_100_entropy_4pred = y_pred

from sklearn.metrics import accuracy_score
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
Test Accuracy:1.000000

In [456]:
cla_forest = RandomForestClassifier(n_estimators = 100,criterion ='gini',max_depth = 4)
cla_forest.fit(X_train,y_train)
#Predict 
y_pred = cla_forest.predict(X_test)
print(y_pred)
rt_100_gini_4pred = y_pred

from sklearn.metrics import accuracy_score
accur=accuracy_score(y_test,y_pred)
print("Test Accuracy:{:.6f}".format(accur))

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
Test Accuracy:1.000000

In [457]:
#dataframe
X_test.head(10)

     Atr9  Atr8  Atr18  Atr17  Atr15  Atr5  Atr11  Atr36
69      4     4      4      4      4     4      4      0
77      3     1      3      3      3     2      1      3
123     0     0      0      0      0     0      0      0
97      0     0      0      0      0     0      0      0
46      3     3      3      3      3     3      3      4
151     0     0      1      1      1     1      1      0
7       3     3      3      2      4     2      4      1
26      4     3      3      3      4     3      3      4
126     0     0      0      0      0     0      0      0
11      4     4      4      4      4     4      4      4

In [458]:
X_test.reset_index(inplace=True,drop =True)
X_test.head(10)

   Atr9  Atr8  Atr18  Atr17  Atr15  Atr5  Atr11  Atr36
0     4     4      4      4      4     4      4      0
1     3     1      3      3      3     2      1      3
2     0     0      0      0      0     0      0      0
3     0     0      0      0      0     0      0      0
4     3     3      3      3      3     3      3      4
5     0     0      1      1      1     1      1      0
6     3     3      3      2      4     2      4      1
7     4     3      3      3      4     3      3      4
8     0     0      0      0      0     0      0      0
9     4     4      4      4      4     4      4      4

In [459]:
y_test.head(10)

69     1
77     1
123    0
97     0
46     1
151    0
7      1
26     1
126    0
11     1
Name: Class, dtype: int64

In [460]:
y_test.head(10)

69     1
77     1
123    0
97     0
46     1
151    0
7      1
26     1
126    0
11     1
Name: Class, dtype: int64

In [461]:
y_test = [x for x in y_test]
print(y_test)

[1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0]

In [462]:
X_test['y_test'] = pd.Series(y_test)

C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [463]:
X_test

    Atr9  Atr8  Atr18  Atr17  Atr15  Atr5  Atr11  Atr36  y_test
0      4     4      4      4      4     4      4      0       1
1      3     1      3      3      3     2      1      3       1
2      0     0      0      0      0     0      0      0       0
3      0     0      0      0      0     0      0      0       0
4      3     3      3      3      3     3      3      4       1
5      0     0      1      1      1     1      1      0       0
6      3     3      3      2      4     2      4      1       1
7      4     3      3      3      4     3      3      4       1
8      0     0      0      0      0     0      0      0       0
9      4     4      4      4      4     4      4      4       1
10     0     0      0      1      0     0      0      0       0
11     4     4      4      4      4     4      4      2       1
12     0     0      1      1      1     0      1      0       0
13     0     0      0      1      0     0      0      0       0
14     3     4      4      4      3     4      4      4       1
15     0     0      0      1      2     0      1      0       0
16     0     0      0      0      0     0      0      0       0
17     0     0      0      0      0     0      0      0       0
18     4     4      3      4      4     2      4      4       1
19     3     2      2      4      3     4      4      4       1
20     0     0      0      0      0     0      0      0       0
21     0     0      0      0      0     0      0      0       0
22     0     0      0      0      1     0      1      0       0
23     1     1      0      0      0     1      1      0       0
24     4     4      4      3      4     4      4      4       1
25     3     3      3      4      3     4      4      4       1
26     1     1      0      0      0     0      0      0       0
27     0     0      0      0      0     0      0      0       0
28     3     2      2      3      3     3      3      4       1
29     3     2      2      3      3     3      3      4       1
30     3     3      3      4      3     4      4      3       1
31     3     3      3      3      3     3      3      4       1
32     0     1      0      0      0     0      0      0       0
33     0     0      0      0      0     0      0      1       0

In [464]:
X_test['lin_reg_pred'] = pd.Series(lin_reg_pred)
X_test['knn_pred'] = pd.Series(knn_pred)
X_test['naive_pred'] = pd.Series(naive_pred)
X_test['SVM_rbf_auto_4pred'] = pd.Series(SVM_rbf_auto_4pred)
X_test['SVM_rbf_scale_4pred'] = pd.Series(SVM_rbf_scale_4pred)
X_test['SVM_rbf_auto_3pred'] = pd.Series(SVM_rbf_auto_3pred)
X_test['SVM_rbf_scale_3pred '] = pd.Series(SVM_rbf_scale_3pred)
X_test['SVM_linear_auto_3pred'] = pd.Series(SVM_linear_auto_3pred)
X_test['SVM_linear_scale_3pred'] = pd.Series(SVM_linear_scale_3pred)
X_test['SVM_sigmoid_auto_3pred'] = pd.Series(SVM_sigmoid_auto_3pred)
X_test['SVM_sigmoid_scale_3pred'] = pd.Series(SVM_sigmoid_scale_3pred)
X_test['SVM_sigmoid_auto_4pred'] = pd.Series(SVM_sigmoid_auto_4pred)
X_test['SVM_sigmoid_scale_4pred'] = pd.Series(SVM_sigmoid_scale_4pred)
X_test['dt_pred'] = pd.Series(dt_pred)
X_test['dt_entropy_3_random_pred'] = pd.Series(dt_entropy_3_random_pred)
X_test['dt_entropy_pred'] = pd.Series(dt_entropy_pred)
X_test['dt_entropy_4_random_pred'] = pd.Series(dt_entropy_4_random_pred)
X_test['rt_100_pred'] = pd.Series(rt_100_pred)
X_test['rt_100_entropy_4pred'] = pd.Series(rt_100_entropy_4pred)
X_test['rt_100_gini_4pred'] = pd.Series(rt_100_gini_4pred)

C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Asus 1\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [465]:
X_test

,Atr9,Atr8,Atr18,Atr17,Atr15,Atr5,Atr11,Atr36,y_test,lin_reg_pred,...,SVM_sigmoid_scale_3pred,SVM_sigmoid_auto_4pred,SVM_sigmoid_scale_4pred,dt_pred,dt_entropy_3_random_pred,dt_entropy_pred,dt_entropy_4_random_pred,rt_100_pred,rt_100_entropy_4pred,rt_100_gini_4pred
0,4,4,4,4,4,4,4,0,1,0.859134,...,1,0,1,1,1,1,1,1,1,1
1,3,1,3,3,3,2,1,3,1,0.983412,...,1,1,1,1,1,1,1,1,1,1
2,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
4,3,3,3,3,3,3,3,4,1,0.998508,...,1,1,1,1,1,1,1,1,1,1
5,0,0,1,1,1,1,1,0,0,0.281643,...,1,1,1,1,0,1,0,0,0,0
6,3,3,3,2,4,2,4,1,1,0.826793,...,1,1,1,1,1,1,1,1,1,1
7,4,3,3,3,4,3,3,4,1,1.040972,...,1,1,1,1,1,1,1,1,1,1
8,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
9,4,4,4,4,4,4,4,4,1,1.210907,...,1,0,1,1,1,1,1,1,1,1
10,0,0,0,1,0,0,0,0,0,0.105670,...,0,0,0,0,0,0,0,0,0,0
11,4,4,4,4,4,4,4,2,1,1.035020,...,1,0,1,1,1,1,1,1,1,1
12,0,0,1,1,1,0,1,0,0,0.363309,...,1,1,1,0,0,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0.105670,...,0,0,0,0,0,0,0,0,0,0
14,3,4,4,4,3,4,4,4,1,1.168443,...,1,0,1,1,1,1,1,1,1,1
15,0,0,0,1,2,0,1,0,0,0.233016,...,1,1,1,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
18,4,4,3,4,4,2,4,4,1,1.223180,...,1,0,1,1,1,1,1,1,1,1
19,3,2,2,4,3,4,4,4,1,1.029127,...,1,1,1,1,1,1,1,1,1,1
20,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,1,0,1,0,0,0.116118,...,0,1,0,0,0,0,0,0,0,0
23,1,1,0,0,0,1,1,0,0,-0.046021,...,1,1,1,0,0,0,0,0,0,0
24,4,4,4,3,4,4,4,4,1,1.114776,...,1,0,1,1,1,1,1,1,1,1
25,3,3,3,4,3,4,4,4,1,1.098785,...,1,0,1,1,1,1,1,1,1,1
26,1,1,0,0,0,0,0,0,0,-0.050166,...,0,1,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0.009539,...,0,0,0,0,0,0,0,0,0,0
28,3,2,2,3,3,3,3,4,1,0.928851,...,1,1,1,1,1,1,1,1,1,1
29,3,2,2,3,3,3,3,4,1,0.928851,...,1,1,1,1,1,1,1,1,1,1
30,3,3,3,4,3,4,4,3,1,1.010842,...,1,0,1,1,1,1,1,1,1,1
31,3,3,3,3,3,3,3,4,1,0.998508,...,1,1,1,1,1,1,1,1,1,1
32,0,1,0,0,0,0,0,0,0,-0.071863,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,1,0,0.097482,...,0,1,0,0,0,0,0,0,0,0

In [466]:
X_test.to_csv('divorce22.csv')